
version: '3.8'
services:
  zabbix-postgres:
    image: postgres:alpine
    container_name: zabbix-postgres
    networks:
      - zabbix-net
    volumes:
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    environment:
      POSTGRES_PASSWORD: zabbix
      POSTGRES_USER: zabbix

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-latest
    container_name: zabbix-server
    networks:
      - zabbix-net
    depends_on:
      - zabbix-postgres
    ports:
      - "10051:10051"
    volumes:
      - /var/lib/zabbix/alertscripts:/usr/lib/zabbix/alertscripts
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_HISTORYSTORAGETYPES: log,text #Zabbix configuration variables
      ZBX_DEBUGLEVEL: 1
      ZBX_HOUSEKEEPINGFREQUENCY: 1
      ZBX_MAXHOUSEKEEPERDELETE: 5000
      PHP_TZ: "Europe/Chisinau"

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-latest
    container_name: zabbix-web
    networks:
      - zabbix-net
    depends_on:
      - zabbix-server
    ports:
      - "80:8080"
      - "443:8443"
    volumes:
      - /var/lib/zabbix/timezone:/etc/timezone
      - /var/lib/zabbix/localtime:/etc/localtime
    environment:
      DB_SERVER_HOST: zabbix-postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      ZBX_MAXEXECUTIONTIME: 500
      PHP_TZ: Europe/Chisinau

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    privileged: true
    # network_mode: "host"
    networks:
      - zabbix-net
    restart: unless-stopped
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: Zabbix-Agent
  # adminer:  #Optional for accessing databases
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

networks:
  zabbix-net:
    driver: bridge
